package exceptions

import "errors"

var ErrUserNotFound = errors.New("user not found")
